/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 02 19:50:40 GMT 2025
 */

package test;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import test.Stack;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Stack_ESTest extends Stack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack stack0 = new Stack(222);
      stack0.push(222);
      int int0 = stack0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Stack stack0 = new Stack(832);
      stack0.push(0);
      int int0 = stack0.pop();
      assertTrue(stack0.isEmpty());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Stack stack0 = new Stack(491);
      stack0.push((-970));
      int int0 = stack0.pop();
      assertEquals(0, stack0.size());
      assertEquals((-970), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Stack stack0 = new Stack(832);
      stack0.push(0);
      int int0 = stack0.peek();
      assertEquals(1, stack0.size());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Stack stack0 = new Stack(491);
      stack0.push((-970));
      int int0 = stack0.peek();
      assertEquals(1, stack0.size());
      assertEquals((-970), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack stack0 = null;
      try {
        stack0 = new Stack((-863));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("test.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack stack0 = new Stack(222);
      stack0.push(222);
      boolean boolean0 = stack0.isEmpty();
      assertEquals(1, stack0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack stack0 = new Stack(222);
      stack0.push(222);
      int int0 = stack0.peek();
      assertEquals(1, stack0.size());
      assertEquals(222, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Stack stack0 = new Stack(222);
      int int0 = stack0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Stack stack0 = new Stack(0);
      boolean boolean0 = stack0.isFull();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Stack stack0 = new Stack(222);
      boolean boolean0 = stack0.isFull();
      assertFalse(boolean0);
      assertTrue(stack0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Stack stack0 = new Stack(0);
      boolean boolean0 = stack0.isEmpty();
      assertTrue(stack0.isFull());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Stack stack0 = new Stack(1714);
      stack0.push(1714);
      stack0.pop();
      // Undeclared exception!
      try { 
        stack0.peek();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stack is empty
         //
         verifyException("test.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Stack stack0 = new Stack(0);
      // Undeclared exception!
      try { 
        stack0.pop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stack is empty
         //
         verifyException("test.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Stack stack0 = new Stack(0);
      // Undeclared exception!
      try { 
        stack0.push(0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stack is full
         //
         verifyException("test.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[6];
      Stack.main(stringArray0);
      assertEquals(6, stringArray0.length);
  }
}
